### ISSUE TITLE
Get Travis CI builds working

### ISSUE THREAD

**Issue by aried3r** [expectedbehavior/acts_as_archival#27]
It seems this repository is being tested on Travis CI, but with the default config, which fails because no databases are being set up etc.

I don't know enough about Travis CI in conjunction with Appraisals to really work on it. But I think one of the problems is also the `db_setup` script, which asks for user input for the MySQL DB instead of using the values in `test/database.yml`.

**Comment by janxious** [comment]
As mentioned in #26, it's weird we have this and it's not working. I'm not sure why it was added and not removed after it didn't work. I suspect all that needs to happen is adding appropriate services to the travis config (sqlite, pg, and mysql) and then as you say, using those database settings. I have invested very little time in travis for this project because the test script worked locally flawlessly. Anyway, I'd love for someone to make this problem go away. :D Happy to help however I can

**Comment by janxious** [comment]
Fixed by #28
